//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RG39.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RG39.Lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT_TAB {
            get {
                return ResourceManager.GetString("ABOUT_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load this game:.
        /// </summary>
        public static string CANNOT_LOAD_GAME_MSG {
            get {
                return ResourceManager.GetString("CANNOT_LOAD_GAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to clear games from list?.
        /// </summary>
        public static string CLEAR_LIST_MSG {
            get {
                return ResourceManager.GetString("CLEAR_LIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string CLEAR_LIST_TITLE {
            get {
                return ResourceManager.GetString("CLEAR_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FILENAME_COL {
            get {
                return ResourceManager.GetString("FILENAME_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FROM_COL {
            get {
                return ResourceManager.GetString("FROM_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GAMES_TAB {
            get {
                return ResourceManager.GetString("GAMES_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Epic Games library?.
        /// </summary>
        public static string LOAD_EPIC_LIB_MSG {
            get {
                return ResourceManager.GetString("LOAD_EPIC_LIB_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Steam library?.
        /// </summary>
        public static string LOAD_STEAM_LIB_MSG {
            get {
                return ResourceManager.GetString("LOAD_STEAM_LIB_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple instances of this program are not allowed..
        /// </summary>
        public static string MULTI_INSTANCE_MSG {
            get {
                return ResourceManager.GetString("MULTI_INSTANCE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not found].
        /// </summary>
        public static string NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove:.
        /// </summary>
        public static string REMOVE_GAME_MSG {
            get {
                return ResourceManager.GetString("REMOVE_GAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was already added..
        /// </summary>
        public static string REPEATED_GAME_MSG {
            get {
                return ResourceManager.GetString("REPEATED_GAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated.
        /// </summary>
        public static string REPEATED_TITLE {
            get {
                return ResourceManager.GetString("REPEATED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search folder.
        /// </summary>
        public static string SEARCH_FOLDER_TITLE {
            get {
                return ResourceManager.GetString("SEARCH_FOLDER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select executable.
        /// </summary>
        public static string SEL_EXE_TITLE {
            get {
                return ResourceManager.GetString("SEL_EXE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS_TAB {
            get {
                return ResourceManager.GetString("SETTINGS_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string START_BTN {
            get {
                return ResourceManager.GetString("START_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TYPE_COL {
            get {
                return ResourceManager.GetString("TYPE_COL", resourceCulture);
            }
        }
    }
}
