name: "Create new release"

on:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  PROJECT_PATH: RandomGameLauncher/RandomGameLauncher.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore -r win-x64

      - name: Package release
        run: |
          cd RandomGameLauncher/bin/Release/net8.0-windows*/win-x64/
          7z a ../../../../../RandomGameLauncher.zip -r ./*

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release Artifact
          path: ./RandomGameLauncher.zip

      - name: Create GitHub release
        id: create_github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Attach release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_github_release.outputs.upload_url }}
          asset_path: ./RandomGameLauncher.zip
          asset_name: RandomGameLauncher.zip
          asset_content_type: application/zip
